const IMAGES_BASE_URL = "http://localhost:3000/images";

export const images = {
    outside1: `${IMAGES_BASE_URL}/outside1.jpeg`,
    outside2: `${IMAGES_BASE_URL}/outside2.jpeg`,
    outside3: `${IMAGES_BASE_URL}/outside3.jpeg`,
    outside4: `${IMAGES_BASE_URL}/outside4.png`,
    inside1: `${IMAGES_BASE_URL}/inside1.jpeg`,
    inside2: `${IMAGES_BASE_URL}/inside2.jpeg`,
    inside3: `${IMAGES_BASE_URL}/inside3.jpeg`,
    peopleInside: `${IMAGES_BASE_URL}/peopleInside.png`,
    intro: `${IMAGES_BASE_URL}/intro.jpeg`,
    video: `${IMAGES_BASE_URL}/video.jpeg`,
    insidePanorama: `${IMAGES_BASE_URL}/insidePanorama.png`,
    hotTube: `${IMAGES_BASE_URL}/hotTube.jpeg`,
    breakfast1: `${IMAGES_BASE_URL}/breakfast1.jpeg`,
    breakfast2: `${IMAGES_BASE_URL}/breakfast2.jpeg`,
    dinner1: `${IMAGES_BASE_URL}/dinner1.jpeg`,
    areaPanorama: `${IMAGES_BASE_URL}/areaPanorama.png`,
    nature1: `${IMAGES_BASE_URL}/nature1.jpeg`,
    nature2: `${IMAGES_BASE_URL}/nature2.jpeg`,
    town1: `${IMAGES_BASE_URL}/town1.jpeg`,
    restaurant1: `${IMAGES_BASE_URL}/restaurant1.jpeg`,
    road1: `${IMAGES_BASE_URL}/road1.jpeg`,
    road2: `${IMAGES_BASE_URL}/road2.jpeg`,
    map: `${IMAGES_BASE_URL}/map.png`,
    hutPicture: `${IMAGES_BASE_URL}/hutPicture.png`,
    womanPaintHut: `${IMAGES_BASE_URL}/womanPaintHut.png`,
    empty: `${IMAGES_BASE_URL}/.png`,
};
