const ICON_BASE_URL = "http://localhost:3000/assets/svg";
const FLAG_FOLDER_URL = "flags";

export const iconService = {
    bedding_and_towels: `${ICON_BASE_URL}/bedding_and_towels.svg`,
    breathtaking_views: `${ICON_BASE_URL}/breathtaking_views.svg`,
    coffee_machine: `${ICON_BASE_URL}/coffee_machine.svg`,
    electric_tea_kettle: `${ICON_BASE_URL}/electric_tea_kettle.svg`,
    floor_heating: `${ICON_BASE_URL}/floor_heating.svg`,
    flushing_toilets: `${ICON_BASE_URL}/flushing_toilets.svg`,
    fridge: `${ICON_BASE_URL}/fridge.svg`,
    kitchen: `${ICON_BASE_URL}/kitchen.svg`,
    parking: `${ICON_BASE_URL}/parking.svg`,
    plug: `${ICON_BASE_URL}/plug.svg`,
    shower: `${ICON_BASE_URL}/shower.svg`,
    wifi: `${ICON_BASE_URL}/wifi.svg`,
    instagram: `${ICON_BASE_URL}/instagram.svg`,
    facebook: `${ICON_BASE_URL}/facebook.svg`,
    twitter: `${ICON_BASE_URL}/twitter.svg`,
    rightArrow: `${ICON_BASE_URL}/rightArrow.svg`,
    rightArrowDisabled: `${ICON_BASE_URL}/rightArrowDisabled.svg`,
    leftArrow: `${ICON_BASE_URL}/leftArrow.svg`,
    leftArrowDisabled: `${ICON_BASE_URL}/leftArrowDisabled.svg`,
    geopoint: `${ICON_BASE_URL}/geopoint.svg`,
    heart: `${ICON_BASE_URL}/heart.svg`,
    arrowDown: `${ICON_BASE_URL}/arrowDown.svg`,
    plus: `${ICON_BASE_URL}/plus.svg`,
    checkMark: `${ICON_BASE_URL}/checkMark.svg`,
    germany: `${ICON_BASE_URL}/${FLAG_FOLDER_URL}/de.svg`,
    denmark: `${ICON_BASE_URL}/${FLAG_FOLDER_URL}/dk.svg`,
    greatBritain: `${ICON_BASE_URL}/${FLAG_FOLDER_URL}/gb.svg`,
    russia: `${ICON_BASE_URL}/${FLAG_FOLDER_URL}/ru.svg`,
};
